version: '3.8'

services:

  backend:
    #build: ./backend
    image: index.docker.io/jsamec/backend:latest
    restart: always
    command: uvicorn app.temad_api:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    
  frontend:
    #build: ./frontend
    image: index.docker.io/jsamec/frontend:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config:
